# -*- coding: utf-8 -*-
"""MLlab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNK6784FH9FwGV_-NHkXS8XijK8x7cKT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

housing = fetch_california_housing(as_frame=True)
df = housing.frame

df.head()
df.info()
df.describe()
df.isnull().sum()

X=df.drop("MedHouseVal",axis=1)
y=df["MedHouseVal"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

model=LinearRegression()
model.fit(X_train_scaled,y_train)
y_pred=model.predict(X_test_scaled)

mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

ridge=Ridge(alpha=1.0)
ridge.fit(X_train_scaled,y_train)
ridge_pred=ridge.predict(X_test_scaled)

lasso=Lasso(alpha=0.1)
lasso.fit(X_train_scaled,y_train)
lasso_pred=lasso.predict(X_test_scaled)

plt.figure(figsize=(8,6))
plt.scatter(y_test,y_pred,color='blue',alpha=0.5)
# Ideal prediction line
plt.plot([y_test.min(), y_test.max()],[y_test.min(),y_test.max()], color='red', linewidth=2)
plt.xlabel("Actual House Price")
plt.ylabel("Predicted House Price")
plt.title("Actual vs Predicted House Prices")
plt.grid(True)
plt.show()

residuals = y_test - y_pred
plt.figure(figsize=(8,6))
plt.scatter(y_pred, residuals, color='green', alpha=0.5)
plt.axhline(y=0, color='red', linestyle='--', linewidth=2)
plt.xlabel("Predicted House Price")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred, alpha=0.5, label="Linear")

plt.scatter(y_test, ridge_pred, alpha=0.5, label="Ridge")
plt.scatter(y_test, lasso_pred, alpha=0.5, label="Lasso")
plt.plot([y_test.min(), y_test.max()], [y_test.min(),
y_test.max()], 'r--')
plt.xlabel("Actual House Price")
plt.ylabel("Predicted House Price")
plt.title("Comparison of Regression Models")
plt.legend()
plt.show()