# -*- coding: utf-8 -*-
"""MLlab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14P5g5cE6q6KRU07yCwHDJyIXmDuaGHdi
"""

from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

X = data.data
y = data.target

print(X.shape)
print(y.shape)

import pandas as pd

# To view the first few rows of the data, you can create a DataFrame from X
df = pd.DataFrame(X)
print(df.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

coefficients = pd.DataFrame({
    "Feature": data.feature_names,
    "Coefficient": model.coef_[0]
})

# ==========================================
# Lab Session 4: Logistic Regression
# ==========================================

# Task 1: Load the Dataset
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)
import pandas as pd
import numpy as np

# Load dataset
data = load_breast_cancer()

X = data.data
y = data.target

# ==========================================
# Task 2: Explore the Dataset
# ==========================================

print("===== Dataset Exploration =====")
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

# Convert to DataFrame
df = pd.DataFrame(X, columns=data.feature_names)

print("\nFirst Five Rows:")
print(df.head())

print("\nNumber of Samples:", X.shape[0])
print("Number of Features:", X.shape[1])
print("Number of Classes:", len(np.unique(y)))

print("\nClass Names:", data.target_names)

# ==========================================
# Task 3: Split the Dataset
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples:", X_train.shape[0])
print("Testing Samples:", X_test.shape[0])

# ==========================================
# Task 4: Standardize Features
# ==========================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\nFeature Scaling Completed.")

# ==========================================
# Task 5: Train Logistic Regression Model
# ==========================================

model = LogisticRegression(random_state=42)

model.fit(X_train_scaled, y_train)

print("\nModel Training Completed.")

# ==========================================
# Task 6: Make Predictions
# ==========================================

y_pred = model.predict(X_test_scaled)

print("\nPredictions:")
print(y_pred)

# ==========================================
# Task 7: Evaluate the Model
# ==========================================

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("\n===== Model Evaluation =====")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-score :", f1)

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=data.target_names))

# ==========================================
# Task 8: Interpret Coefficients
# ==========================================

coefficients = pd.DataFrame({
    "Feature": data.feature_names,
    "Coefficient": model.coef_[0]
})

print("\n===== Model Coefficients =====")
print(coefficients)

# Largest Positive Coefficient
largest_positive = coefficients.loc[
    coefficients["Coefficient"].idxmax()
]

# Largest Negative Coefficient
largest_negative = coefficients.loc[
    coefficients["Coefficient"].idxmin()
]

print("\nLargest Positive Coefficient:")
print(largest_positive)

print("\nLargest Negative Coefficient:")
print(largest_negative)

print("\nInterpretation:")
print("Positive coefficient  -> As the feature value increases, the probability of the positive class (Benign) increases.")
print("Negative coefficient  -> As the feature value increases, the probability of the negative class (Malignant) increases.")