# -*- coding: utf-8 -*-
"""MLlab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXrqF-VCQKFEvr8SPP9jVwM-SaE76JFu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url ="https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv";
df = pd.read_csv(url)

df.head()
df.info()
df.describe()

df.isnull().sum()

sns.heatmap(df.isnull(), cbar=False)
plt.show()

df['Age'].fillna(df['Age'].median(), inplace=True)

df['Embarked'].fillna(df['Embarked'].mode()[0],
inplace=True)

df.drop('Cabin', axis=1, inplace=True)

df.select_dtypes(include='object').columns

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

df = pd.get_dummies(df,columns=['Embarked'],drop_first=True)

num_cols = ['Age', 'Fare']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

df[['Age','Fare']].head()

sns.boxplot(x=df['Fare'])
plt.show()

Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Fare'] < lower)|(df['Fare'] > upper)]
print(len(outliers))

df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)

X = df.drop('Survived', axis=1)
y = df['Survived']

print(X.shape)
print(y.shape)

import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer

# Load dataset
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

# ---------------------------
# Exercise 1: Count Male and Female Passengers
# ---------------------------
gender_count = df['Sex'].value_counts()
print("Male and Female Passenger Count:")
print(gender_count)

# ---------------------------
# Exercise 2: Average Age Before and After Filling Missing Values
# ---------------------------
avg_age_before = df['Age'].mean()

# Fill missing values with mean age
df['Age_filled'] = df['Age'].fillna(df['Age'].mean())

avg_age_after = df['Age_filled'].mean()

print("\nAverage Age Before Filling Missing Values:", avg_age_before)
print("Average Age After Filling Missing Values:", avg_age_after)

# ---------------------------
# Exercise 3: Detect Outliers in Age Column (IQR Method)
# ---------------------------
Q1 = df['Age_filled'].quantile(0.25)
Q3 = df['Age_filled'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Age_filled'] < lower_bound) | (df['Age_filled'] > upper_bound)]

print("\nNumber of Outliers in Age Column:", len(outliers))
print(outliers[['Age_filled']])

# ---------------------------
# Exercise 4: Apply Min-Max Scaling
# ---------------------------
scaler = MinMaxScaler()

df['Age_MinMax'] = scaler.fit_transform(df[['Age_filled']])

print("\nFirst 5 Rows After Min-Max Scaling:")
print(df[['Age_filled', 'Age_MinMax']].head())

# ---------------------------
# Exercise 5: Compare Label Encoding and One-Hot Encoding
# ---------------------------

# Label Encoding
le = LabelEncoder()
df['Sex_LabelEncoded'] = le.fit_transform(df['Sex'])

print("\nLabel Encoding:")
print(df[['Sex', 'Sex_LabelEncoded']].head())

# One-Hot Encoding
ohe = pd.get_dummies(df['Sex'], prefix='Sex')

print("\nOne-Hot Encoding:")
print(ohe.head())

# Comparison
print("\nComparison:")
print(df[['Sex', 'Sex_LabelEncoded']].head())
print(ohe.head())

